# Generated by Django 3.2 on 2021-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('1', 'Абхазия'), ('2', 'Россия'), ('3', 'США')], default='2', max_length=1),
        ),
    ]
